spring:
  application:
    name: JobPortal

  datasource:
    url: jdbc:postgresql://localhost:5432/jobportal
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 60289
