spring:
  application:
    name: JobPortal

  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/jobportal
    username: titus
    password: 123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: vkdy+vIJzGMEvl2A//Uv2FfXZ8/Wa9SJeiHnS0DA4yg=
  expiration: 3600000
  tokenPrefix: Bearer
  headerString: Authorization

server:
  port: 60289

  mail:
    host: smtp.gmail.com
    port: 587
    username: murithititus510@gmail.com
    password: eokb jcuy mgtl tswm
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
